### PR TITLE
Add ability to run xversion "make check"

### PR DESCRIPTION
**Pull request by rhc54**
Add the tests currently being used in "make check" and track that
cross-version support as well.

Signed-off-by: Ralph Castain <rhc@pmix.org>

### CODE REVIEW

**Comment by rhc54** [comment]
@jjhursey Please take a look at this. I checked master against v3.1 and it ran clean with the following summary:
```shell
============================== Summary (Make Check) ==============================
Run PASS: master -> v3.1
Run PASS: master -> v3.1
Run PASS: master -> v3.1
Run PASS: master -> v3.1
Run PASS: master -> v3.1
Run PASS: master -> v3.1
Run PASS: master -> v3.1
Run PASS: master -> v3.1
Run PASS: master -> v3.1
Run PASS: master -> v3.1
Run PASS: master -> v3.1
Run PASS: master -> v3.1
Run PASS: master -> v3.1
Run PASS: master -> v3.1
Run PASS: master -> v3.1
Run PASS: master -> v3.1
```
Will perform a full check now. I think we need to improve the output a bit, though, as we really don't want to report "pass" for each individual test or it can be confusing - or maybe we just need to add some descriptor about each test so it is clearer?

**Comment by rhc54** [comment]
Well, it isn't any real surprise that it failed miserably. I think there are a few things we need to do to really complete the assessment and this script:

- [ ] we need an ability to "skip" individual check tests as some of them (e.g., resolving peers) are known not be work on some branches (e.g., v1.2)

- [ ] backport "make check" to every release branch and independently assess their situation. This can drive the above table of "skip" tests.

- [ ] update the tests in every release branch, where applicable. I'm not sure that the fixes required to accurately report the test's exit status made it everywhere as I'm seeing error log output from tests labeled "success"

- [ ] add a "timeout" ability to the script - we are hitting infinite loops in at least a couple of combinations

Once we get this done and can complete a full test run, we'll need to assess the results and decide on a path forward. It may be we just need to document what doesn't work on some branches, but it looks like we will need to fix some things as the v3.1(server)->master(client) appears to have failures (at least, for now - might again be a question of ensuring tests are updated)

**Comment by jjhursey** [comment]
I split the CI into two parts:
```
"IBM CI (Cross-version)" for client/server
 - Note this should pass now on all PRs.
Retest with:   bot:ibm:xver:retest
```

```
"IBM CI (Cross-version: Tool)" for tool/server
 - Note this will currently fail.
Retest with:   bot:ibm:xvertool:retest
```

Once this PR is merged we can add another one for the `make check` support.

**Comment by rhc54** [comment]
I have this updated and working - here is the current status:
```shell
============================== Summary (Make Check Failures) ==============================
Run ***FAILED***: master -> v3.1  [-n 2 --test-spawn -e ]
Run ***FAILED***: master -> v3.0  [-n 2 --test-spawn -e ]
Run ***FAILED***: master -> v2.2  [-n 2 --test-spawn -e ]
Run ***FAILED***: master -> v2.1  [-n 2 --test-spawn -e ]
Run ***FAILED***: master -> v2.0  [-n 4 --ns-dist 3:1 --fence "[db | 0:;1:]" -e ]
Run ***FAILED***: master -> v2.0  [-n 5 --test-resolve-peers --ns-dist "1:2:2" -e ]
Run ***FAILED***: master -> v1.2  [-n 4 --ns-dist 3:1 --fence "[db | 0:;1:]" -e ]
Run ***FAILED***: master -> v1.2  [-n 5 --test-resolve-peers --ns-dist "1:2:2" -e ]
Run ***FAILED***: master -> v1.2  [-n 5 --test-replace 100:0,1,10,50,99 -e ]
Run ***FAILED***: v3.1 -> master  [-n 2 --test-spawn -e ]
Run ***FAILED***: v3.1 -> v2.0  [-n 4 --ns-dist 3:1 --fence "[db | 0:;1:]" -e ]
Run ***FAILED***: v3.1 -> v2.0  [-n 5 --test-resolve-peers --ns-dist "1:2:2" -e ]
Run ***FAILED***: v3.1 -> v1.2  [-n 5 --test-resolve-peers --ns-dist "1:2:2" -e ]
Run ***FAILED***: v3.1 -> v1.2  [-n 5 --test-replace 100:0,1,10,50,99 -e ]
Run ***FAILED***: v3.0 -> master  [-n 2 --test-spawn -e ]
Run ***FAILED***: v3.0 -> v2.0  [-n 4 --ns-dist 3:1 --fence "[db | 0:;1:]" -e ]
Run ***FAILED***: v3.0 -> v2.0  [-n 5 --test-resolve-peers --ns-dist "1:2:2" -e ]
Run ***FAILED***: v3.0 -> v1.2  [-n 4 --ns-dist 3:1 --fence "[db | 0:;1:]" -e ]
Run ***FAILED***: v3.0 -> v1.2  [-n 5 --test-resolve-peers --ns-dist "1:2:2" -e ]
Run ***FAILED***: v3.0 -> v1.2  [-n 5 --test-replace 100:0,1,10,50,99 -e ]
Run ***FAILED***: v2.2 -> v2.0  [-n 4 --ns-dist 3:1 --fence "[db | 0:;1:]" -e ]
Run ***FAILED***: v2.2 -> v2.0  [-n 5 --test-resolve-peers --ns-dist "1:2:2" -e ]
Run ***FAILED***: v2.2 -> v1.2  [-n 4 --ns-dist 3:1 --fence "[db | 0:;1:]" -e ]
Run ***FAILED***: v2.2 -> v1.2  [-n 5 --test-resolve-peers --ns-dist "1:2:2" -e ]
Run ***FAILED***: v2.2 -> v1.2  [-n 5 --test-replace 100:0,1,10,50,99 -e ]
Run ***FAILED***: v2.1 -> master  [-n 2 --test-spawn -e ]
Run ***FAILED***: v2.1 -> v2.0  [-n 4 --ns-dist 3:1 --fence "[db | 0:;1:]" -e ]
Run ***FAILED***: v2.1 -> v2.0  [-n 5 --test-resolve-peers --ns-dist "1:2:2" -e ]
Run ***FAILED***: v2.1 -> v1.2  [-n 4 --ns-dist 3:1 --fence "[db | 0:;1:]" -e ]
Run ***FAILED***: v2.1 -> v1.2  [-n 5 --test-resolve-peers --ns-dist "1:2:2" -e ]
Run ***FAILED***: v2.1 -> v1.2  [-n 5 --test-replace 100:0,1,10,50,99 -e ]
Run ***FAILED***: v2.0 -> v2.0  [-n 4 --ns-dist 3:1 --fence "[db | 0:0-2;1:0]" -e ]
Run ***FAILED***: v2.0 -> v2.0  [-n 4 --ns-dist 3:1 --fence "[db | 0:;1:0]" -e ]
Run ***FAILED***: v1.2 -> v1.2  [-n 4 --ns-dist 3:1 --fence "[db | 0:0-2;1:0]" -e ]
Run ***FAILED***: v1.2 -> v1.2  [-n 4 --ns-dist 3:1 --fence "[db | 0:;1:0]" -e ]
```
Note that I only have it output the failures as otherwise the list gets ridiculously long. I suspect some of these failures are due to tests that are not appropriate for the given combination, but we probably need to review the list to determine which ones to "prune".

**Comment by rhc54** [comment]
Also note that running the "make-check" tests requires that you specifically request it. I'm going to commit this just so we have the ability to execute it when desired - it shouldn't have any impact on CI as Jenkins doesn't know to turn the tests "on".

**Comment by jjhursey** [comment]
Thanks. I have CI setup, but not enabled for now since it's failing. If you want me to enable it just let me know.

**Pull request merged**
