### PR TITLE
Update xversion to run all "make check" tests

### PR DESCRIPTION
**Pull request by rhc54**
Unfortunately, the "simpleclient" test is not adequate to ensure we
truly have maintained cross-version support. Update the xversion.py
script so it runs the same suite of tests as "make check" does.

Signed-off-by: Ralph Castain <rhc@pmix.org>

### CODE REVIEW

**Comment by rhc54** [comment]
@jjhursey Not sure if your Jenkins test uses the script in this repo or has its own copy? We should update it regardless and ensure we are really testing x-version compatibility.

**Comment by rhc54** [comment]
@jjhursey @artpol84 @karasevb It appears that we get inconsistent results from the pmix_test code - i.e., I see multiple error outputs during execution, but sometimes the code returns a zero status and the test is marked as "passed" and other times it returns a status of 1 and the test is marked as failed.

Is it possible that we have a race condition between the two servers you are simulating? Maybe one has a client fail before the other, or perhaps the one that is in the main process doesn't see the failure but the one that is forked off does? Just throwing some ideas out there - we do need to get to the bottom of this.

**Comment by artpol84** [comment]
@rhc54 can you provide some details about how to reproduce?
Also I think it’ll be good to provide output snippets here

**Comment by rhc54** [comment]
It's rather easy to replicate by just running "make check" in the test subdirectory on master. Output from the command:
```shell
$ make check
Making check in simple
make[1]: Nothing to be done for `check'.
/Applications/Xcode.app/Contents/Developer/usr/bin/make  pmix_test pmix_client pmix_regex pmi_client pmi2_client
make[2]: `pmix_test' is up to date.
make[2]: `pmix_client' is up to date.
make[2]: `pmix_regex' is up to date.
make[2]: `pmi_client' is up to date.
make[2]: `pmi2_client' is up to date.
/Applications/Xcode.app/Contents/Developer/usr/bin/make  check-TESTS
PASS: run_tests00.pl
PASS: run_tests01.pl
PASS: run_tests02.pl
PASS: run_tests03.pl
PASS: run_tests04.pl
PASS: run_tests05.pl
PASS: run_tests06.pl
PASS: run_tests07.pl
PASS: run_tests08.pl
PASS: run_tests09.pl
PASS: run_tests10.pl
PASS: run_tests11.pl
PASS: run_tests12.pl
PASS: run_tests13.pl
PASS: run_tests14.pl
PASS: run_tests15.pl
============================================================================
Testsuite summary for pmix 4.0.0a1
============================================================================
# TOTAL: 16
# PASS:  16
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
```
Now check the actual logs from each test and you'll see entries like this (some debug output was added by me - can be ignored):
```shell
./pmix_test -n 5 --test-resolve-peers --ns-dist "1:2:2" 2>&1
[Ralphs-iMac-2.local:09648] GET JOB DATA
[Ralphs-iMac-2.local:09648] GET JOB DATA
[Ralphs-iMac-2.local:09648] GET JOB DATA
[Ralphs-iMac-2.local:09668] PMIX bfrop:unpack: got type 27 when expecting type 40
[Ralphs-iMac-2.local:09668] PMIX ERROR: PACK-MISMATCH in file gds_hash.c at line 852
[Ralphs-iMac-2.local:09668] PMIX ERROR: PACK-MISMATCH in file client/pmix_client_connect.c at line 399
[Ralphs-iMac-2.local:09666] PMIX bfrop:unpack: got type 27 when expecting type 40
[Ralphs-iMac-2.local:09666] PMIX ERROR: PACK-MISMATCH in file gds_hash.c at line 852
[Ralphs-iMac-2.local:09666] PMIX ERROR: PACK-MISMATCH in file client/pmix_client_connect.c at line 399
[Ralphs-iMac-2.local:09667] PMIX bfrop:unpack: got type 27 when expecting type 40
[Ralphs-iMac-2.local:09667] PMIX ERROR: PACK-MISMATCH in file gds_hash.c at line 852
[Ralphs-iMac-2.local:09667] PMIX ERROR: PACK-MISMATCH in file client/pmix_client_connect.c at line 399
[Ralphs-iMac-2.local:09648] GET JOB DATA
[Ralphs-iMac-2.local:09648] GET JOB DATA
[Ralphs-iMac-2.local:09648] GET JOB DATA
[Ralphs-iMac-2.local:09669] PMIX bfrop:unpack: got type 27 when expecting type 40
[Ralphs-iMac-2.local:09671] PMIX bfrop:unpack: got type 27 when expecting type 40
[Ralphs-iMac-2.local:09669] PMIX ERROR: PACK-MISMATCH in file gds_hash.c at line 852
[Ralphs-iMac-2.local:09669] PMIX ERROR: PACK-MISMATCH in file client/pmix_client_connect.c at line 399
[Ralphs-iMac-2.local:09666] PMIX bfrop:unpack: got type 27 when expecting type 40
[Ralphs-iMac-2.local:09666] PMIX ERROR: PACK-MISMATCH in file gds_hash.c at line 852
[Ralphs-iMac-2.local:09666] PMIX ERROR: PACK-MISMATCH in file client/pmix_client_connect.c at line 399
[Ralphs-iMac-2.local:09671] PMIX ERROR: PACK-MISMATCH in file gds_hash.c at line 852
[Ralphs-iMac-2.local:09671] PMIX ERROR: PACK-MISMATCH in file client/pmix_client_connect.c at line 399
[Ralphs-iMac-2.local:09648] GET JOB DATA
[Ralphs-iMac-2.local:09648] GET JOB DATA
[Ralphs-iMac-2.local:09648] GET JOB DATA
[Ralphs-iMac-2.local:09648] GET JOB DATA
[Ralphs-iMac-2.local:09667] PMIX bfrop:unpack: got type 27 when expecting type 40
[Ralphs-iMac-2.local:09667] PMIX ERROR: PACK-MISMATCH in file gds_hash.c at line 852
[Ralphs-iMac-2.local:09669] PMIX bfrop:unpack: got type 27 when expecting type 40
[Ralphs-iMac-2.local:09667] PMIX ERROR: PACK-MISMATCH in file client/pmix_client_connect.c at line 399
[Ralphs-iMac-2.local:09671] PMIX bfrop:unpack: got type 27 when expecting type 40
[Ralphs-iMac-2.local:09669] PMIX ERROR: PACK-MISMATCH in file gds_hash.c at line 852
[Ralphs-iMac-2.local:09671] PMIX ERROR: PACK-MISMATCH in file gds_hash.c at line 852
[Ralphs-iMac-2.local:09669] PMIX ERROR: PACK-MISMATCH in file client/pmix_client_connect.c at line 399
[Ralphs-iMac-2.local:09671] PMIX ERROR: PACK-MISMATCH in file client/pmix_client_connect.c at line 399
[Ralphs-iMac-2.local:09668] PMIX bfrop:unpack: got type 27 when expecting type 40
[Ralphs-iMac-2.local:09668] PMIX ERROR: PACK-MISMATCH in file gds_hash.c at line 852
[Ralphs-iMac-2.local:09668] PMIX ERROR: PACK-MISMATCH in file client/pmix_client_connect.c at line 399
==9648== test_server.c:server_finalize: Test finished OK!

CODE 0
```
The test clearly failed but the output says it "finished OK" and the return status code from the test is zero, leading the script to believe the test passed.

A cross-version test with the changes in this PR yields things like this:
```shell
Command: /Users/rhc/pmix/pmix-tests/crossversion/pmix-master/test/pmix_test -n 4 --ns-dist 3:1 --fence "[db | 0:;1:]" -e /Users/rhc/pmix/pmix-tests/crossversion/pmix-v3.0/test/pmix_client
ERROR [test_fence.c:190:test_fence]: smoky_nspace-0:1: PMIx_Get failed: -17 from smoky_nspace-1:3, key key-f0:0
ERROR [test_fence.c:192:test_fence]: smoky_nspace-0:1: PMIx_Get failed (-1) from smoky_nspace-1:3
ERROR [pmix_client.c:146:main]: smoky_nspace-0:1 Fence test failed: -1
ERROR [test_fence.c:190:test_fence]: smoky_nspace-0:0: PMIx_Get failed: -17 from smoky_nspace-1:3, key key-f0:0
ERROR [test_fence.c:192:test_fence]: smoky_nspace-0:0: PMIx_Get failed (-1) from smoky_nspace-1:3
ERROR [test_fence.c:190:test_fence]: smoky_nspace-0:2: PMIx_Get failed: -17 from smoky_nspace-1:3, key key-f0:0
ERROR [pmix_client.c:146:main]: smoky_nspace-0:0 Fence test failed: -1
ERROR [test_fence.c:190:test_fence]: smoky_nspace-1:0: PMIx_Get failed: -17 from smoky_nspace-1:3, key key-f0:0
ERROR [test_fence.c:192:test_fence]: smoky_nspace-0:2: PMIx_Get failed (-1) from smoky_nspace-1:3
ERROR [pmix_client.c:146:main]: smoky_nspace-0:2 Fence test failed: -1
ERROR [test_fence.c:192:test_fence]: smoky_nspace-1:0: PMIx_Get failed (-1) from smoky_nspace-1:3
ERROR [pmix_client.c:146:main]: smoky_nspace-1:0 Fence test failed: -1
==60748== ERROR [cli_stages.c:159:cli_cleanup]: rank 1 with state 1 unexpectedly terminated.
==60748== ERROR [server_callbacks.c:91:finalized]: double termination of rank 1
==60748== ERROR [pmix_test.c:162:main]: Test was aborted!
==60748== ERROR [server_callbacks.c:87:finalized]: cannot found rank 0
==60748== ERROR [server_callbacks.c:91:finalized]: double termination of rank 0
==60748== ERROR [server_callbacks.c:91:finalized]: double termination of rank 2
==60748== test_server.c:server_finalize: Test finished OK!
        RETURNED ERROR STATUS 1
```
which reports that the test "finished ok" - but it at least returned a non-zero status. Confusing, but the script at least knows that something went wrong.

I'm seeing multiple errors across all combinations of branches, some returning an error status of 1 and others returning zero but with errors reported in the log. Some of the changes I've made here look like they are resulting in more consistency, which is good - unfortunately, it looks like we have some work to do to fix the breakage. In fairness, we weren't testing more than the simplest options and so these errors weren't being exposed.

I'll post more tomorrow when I'm able to run more tests.

**Comment by jjhursey** [comment]
The PMIx cross version test [container](https://github.com/jjhursey/pmix-xver-tester) uses the version of the `xversion.py` script in the pmix-tests repo. It updates itself [here](https://github.com/jjhursey/pmix-xver-tester/blob/master/bin/run-xversion.sh#L64-L65) in the script that it runs from the pmix-tests master branch.

**Comment by jjhursey** [comment]
Per teleconf:
 * We need to level set on why `make check` is failing and assess what is going on. We might hold v3.1.3 until this is resolved or focus on a quick v3.1.4 with this fix shortly afterward.
 * Let's keep the discussion thread here (some additional notes in https://github.com/pmix/pmix/pull/1193#issuecomment-487294576 )

**Comment by jjhursey** [comment]
The `make check` issue holding this is now fixed. Will merge in conjunction with PR #7

**Comment by jjhursey** [comment]
Merge conflicts from PR #7 - I'll work on a new PR for this to resolve the conflict. I'm working on some more checking, so I'll do that work with this.

**Comment by rhc54** [comment]
Will be replace with updated version

**Pull request closed without merging**
